### ISSUE TITLE
Peer-to-peer code review Thu 10, 2022

### ISSUE THREAD

**Issue by cynthiainga** [daudi13/Awesome-books#3]
- Add deploy link to your README file

- No data is still preserved in your browser memory. When I reload the page, all the books disappear. Please try to fix it.

But you did a good job so far and courage for the rest

All the Best

**Comment by i-max-xi** [comment]
Please refer to the link https://github.com/daudi13/Awesome-books/pull/2#discussion_r803381963
to access the reply on this issue.
I believe preserving in browser's memory works fine (at least when i access the page)
